name: Kernel Prebuilts CI

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true   

env:
  TZ: Asia/Kolkata
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "alex5402"
          git config --global user.email "alex5402private@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version

      - name: Lets compile
        run: |
          git clone $REPO -b $BRANCH kernel 
          cd kernel
          rm -rf .git
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          bash build.sh
          git clone https://"alex5402":"${GITHUB_TOKEN}"@github.com/alex5402/device_realme_RMX2020-kernel-workflow push
          cp -r out/arch/arm64/boot/Image.gz push
          cd push
          git add .
          git commit -m "RMX2020-kernel: Update kernel prebuilts" -m "- Build Date: $(date)" -s
          git push -f

